### ISSUE TITLE
When piping through watermark, there's no output (and no errors)

### ISSUE THREAD

**Issue by ivantodorovich** [HAKASHUN/gulp-watermark#7]
```js
gulp.task('watermark', function() {
	return gulp.src('src/catalog/**/*.jpg')
	.pipe(watermark({
		image: './src/watermark.original.png'
	}))
	.pipe(gulp.dest('./watermark-example'))
})
```

```
$ gulp watermark
[15:25:35] Using gulpfile ~\...\gulpfile.js
[15:25:35] Starting 'watermark'...
[15:25:42] Finished 'watermark' after 6.07 s
```

The output folders are created, even the subfolders, but there're no files.
If I don't pipe through `watermark`, files are created as expected.

**Comment by leadscloud** [comment]
same error

**Comment by leadscloud** [comment]
solved it . 

https://www.npmjs.com/package/gulp-gm

before use the script, first install gm. but gm need GraphicsMagick
`gulp-gm works best with GraphicsMagick.`

install GraphicsMagick on windows , then is ok.
